version: '3'
services:
  web:
    image: web
    ports:
      - "80:80"
  server:
    image: server

  minio:
    image: minio
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: redis
    ports:
      - "6379:6379"